### ISSUE TITLE
 uPickle does not know how to write [...]

### ISSUE THREAD

**Issue by amnaredo** [amnaredo/test#78]
Hi!

While looking for a nice way to pickle scala objects <-> json to exchange data between play and scala-js enabled client, uPickle seems a good candidate.

Unfortunately, until now I kept getting the error "uPickle does not know how to write..." while trying to picklelise a custom case class (like the 'Thing' example given on the main page) on the JVM (didn't even tried with scalajs).

Finally, I discovered the source of the issue: the version of scala.
While compiling with scala 2.10.4, the message keep popping up, however when using scala 2.11.x it compiles gently.

The configuration is as simple as possible, a standalone sbt project with only one libraryDependency (uPickle), and a single file:

``` scala
case class Buddy(a: Int)
import upickle._

object Blah {
  def blah = {
    write(Buddy(42))
  }
}
```

As a side note, uPickle < 0.2.0 works with 2.10.x (e.g. 0.1.6), not uPickle >= 0.2.0.

Cheers,

Jean Luc

ID: 20
Original Author: jlc

**Comment by amnaredo** [comment]
Could you try using this?

``` scala
libraryDependencies += "org.scalamacros" %% s"quasiquotes" % "2.0.0" % "provided"
```

Not sure why it's necessary to have in your build.sbt, or why it's not necessary with uPickle <0.2.0, but I seem to get

```
error: exception during macro expansion:
java.lang.NoClassDefFoundError: scala/quasiquotes/QuasiquoteCompat$
    at upickle.Macros$.picklerFor(Macros.scala:142)
    at upickle.Macros$.macroWImpl(Macros.scala:45)
```

on the recent version. @xeno-by have you seen this message before?

Original Author: lihaoyi

**Comment by amnaredo** [comment]
Yes, it works with a direct dependency on quasiquotes.

Thanks!

Original Author: jlc

**Comment by amnaredo** [comment]
Hi!

Well, the previous trick works when applied to a standalone project.
Unfortunately, it doesn't work in a play application, neither when compiled for the jvm, nor for scalajs.

Hope it helps!

Original Author: jlc

**Comment by amnaredo** [comment]
Ah, I'm not sure what's going on. I've been using it in multiple spray applications without any problem. For that matter, I didn't need to provide the quasiquotes dependency either =/

Original Author: lihaoyi

**Comment by amnaredo** [comment]
Hmm lemme ask the macros guys to see if i can make sense of this

Original Author: lihaoyi

**Comment by amnaredo** [comment]
Quasiquotes rely on a significant number of helper facilities (so called `SyntacticXXX` objects with apply/unapply methods) in order to transparently handle the variety/overloadedness of scalac's AST. 

In Scala 2.11, these helpers live in `scala-reflect.jar`. In Scala 2.10, we can't put them into `scala-reflect.jar`, so `org.scalamacros %% quasiquotes % 2.0.0` needs to be on the classpath of the compiler when you want to expand macros that use quasiquotes. 

Well, more precisely speaking, if your quasiquotes don't require any helpers, then everything will work just fine w/o the library. Otherwise, (on 2.10) you'll be seeing `NoClassDefFoundError` exceptions.

Original Author: xeno-by

**Comment by amnaredo** [comment]
Is there any way to figure out which parts of the quasiquotes aren't requiring these helpers, or anywhere that this fact is documented? I don't remember reading anywhere that quasiquotes had a runtime dependency, and having them would cause problems when running my code in ScalaJS

Original Author: lihaoyi

**Comment by amnaredo** [comment]
Right now it's not documented. Iirc the situations are really irregular, so I guess the only way of figuring out all of them would be to read the source code. Maybe Denys will advise something. Or you could write a macro that ensures that no helper is called.

Btw why will a dependency on the helper lead to problems with ScalaJS? You don't need the helper at runtime runtime (i.e. when the app runs) - you only need it at compile-time runtime (i.e. when macros expand).

Original Author: xeno-by

**Comment by amnaredo** [comment]
Eh you're right if its a compile time helper scalajs won't mind. Maybe I
should just add the quasiquote dependency to the docs and call it a day
On Aug 30, 2014 1:00 AM, "Eugene Burmako" notifications@github.com wrote:

> Right now it's not documented. Iirc the situations are really irregular,
> so I guess the only way of figuring out all of them would be to read the
> source code. Maybe Denys will advise something. Or you could write a macro
> that ensures that no helper is called.
> 
> Btw why will a dependency on the helper lead to problems with ScalaJS? You
> don't need the helper at runtime runtime (i.e. when the app runs) - you
> only need it at compile-time runtime (i.e. when macros expand).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/lihaoyi/upickle/issues/20#issuecomment-53951974.

Original Author: lihaoyi

**Comment by amnaredo** [comment]
Thanks @lihaoyi  @xeno-by !

As new tests, here several interested scenarios within a freshly generated play application, and an already existing project.

0) generate play

```
activator new upickle-test
```

Add upickle resolver and dependency in build.sbt as described in the main page.

1) add blah() to app/controllers/Application.scala:

```
package controllers

import play.api._
import play.api.mvc._

object Application extends Controller {

  def index = Action {
    Ok(views.html.index("Your new application is ready."))
  }

  def blah = { 
    import upickle._                                                                                                                                                                                                                                                                                                                                                        
    case class Thing(i: Int)
    write(Thing(42))
  }
}
```

Ensure the use of scala to 2.11.1 (in sbt command line), and compile

```
[upickle-test] ++2.11.1
[upickle-test] compile
[error] /Users/jeanluc/tmp/upickle-test/app/controllers/Application.scala:15: uPickle does not know how to write [Thing]s; define an implicit Writer[Thing] to teach it how
[error]     write(Thing(42))
[error]          ^
[error] one error found
```

To fix the error, move import upickle._ and case class declaration up:

```
package controllers

import play.api._
import play.api.mvc._

import upickle._
case class Thing(i: Int)

object Application extends Controller {
```

Recompile:

```
[upickle-test] clean
[upickle-test] $ compile
[info] Updating {file:/Users/jeanluc/tmp/upickle-test/}root...
[info] Resolving jline#jline;2.11 ...
[info] Done updating.
[info] Compiling 5 Scala sources and 1 Java source to /Users/jeanluc/tmp/upickle-test/target/scala-2.11/classes...
[success] Total time: 5 s, completed Sep 2, 2014 3:18:44 PM
```

2) Now, using the latest configuration with scala 2.10.4

```
[upickle-test] ++2.10.4
```

Clean and compile:

```
[error] /Users/jeanluc/tmp/upickle-test/app/controllers/Application.scala:16: uPickle does not know how to write [controllers.Thing]s; define an implicit Writer[controllers.Thing] to teach it how
[error]     write(Thing(42))
[error]          ^
[error] one error found
```

Add dependency on quasiquotes, reload, clean and compile:

```
[upickle-test] reload
[upickle-test] ++2.10.4
[upickle-test] compile
[upickle-test] $ compile
[info] Updating {file:/Users/jeanluc/tmp/upickle-test/}root...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Compiling 5 Scala sources and 1 Java source to /Users/jeanluc/tmp/upickle-test/target/scala-2.10/classes...
[success] Total time: 6 s, completed Sep 2, 2014 3:21:12 PM
```

Good, now if I try to move "import upickle._" within the function, it complains again.

3) Now in my project (much more complex "enterprise application"), by moving the "import upickle._" on top of the other imports, and declaring the case class outside of the scope of the function seems to fix the issue (scala 2.10.4).

All this to say: that the position of the import upickle._ matter...

Hope it helps.

Original Author: jlc

**Comment by amnaredo** [comment]
Ah, well here's one problem: upickle doesn't know how to support local classes, because of [this](https://issues.scala-lang.org/browse/SI-7567). If you move the case class out of the def/class it should work.

I'm not sure why it doesn't work when the import is inside the def, but it probably shouldn't

Original Author: lihaoyi

**Comment by amnaredo** [comment]
@lihaoyi Thanks for the quasiquotes tip. I also had the same problem with Scala 2.10.4.

Wouldn't it be useful to add this info in the README?

Original Author: sebnozzi

**Comment by amnaredo** [comment]
Sure, feel free to send a PR

Original Author: lihaoyi

**Comment by amnaredo** [comment]
@lihaoyi No problem. Will do it later.

Do you have documentation on how to write a custom Writer / Reader?

Original Author: sebnozzi

**Comment by amnaredo** [comment]
Closing this for now, since it seems the problem is "resolved" (lol)

Original Author: lihaoyi
